insert into plays values (109, 'Queens and Kings of Madagascar', 'Paul Sat');
insert into plays values (123, 'Merlin', 'Lee Roy');
insert into plays values (142, 'Key of the tea', 'Max Rogers');
insert into plays values (144, 'ROMEance Comedy', 'Bohring Ashell');
insert into plays values (145, 'Nameless.', 'Note Nul');
insert into reservations values (13, 109, 12, 'Mc Rayleigh Theater');
insert into reservations values (24, 109, 34, 'Mc Rayleigh Theater');
insert into reservations values (37, 145, 84, 'Mc Rayleigh Theater');
insert into reservations values (49, 145, 45, 'Mc Rayleigh Theater');
insert into reservations values (51, 145, 41, 'Mc Rayleigh Theater');
insert into reservations values (68, 123, 3, 'Mc Rayleigh Theater');
insert into reservations values (83, 142, 46, 'Mc Rayleigh Theater');